from __future__ import annotations

TEXTS: dict[str, dict[str, str]] = {
    "uk": {
        "region_prompt": "Обери свій регіон для цін у Stars. Зараз: <b>{region}</b>. Підтверди або зміни 👇",
        "region_choose": "Обери свій регіон — від нього залежить ціна в Stars 👇",
        "region_saved": "Добре, регіон змінила на {region} 💕",
        "language_choose": "Якою мовою тобі зручніше зі мною?",
        "language_saved": "Готово, мову змінила)",
        "public_gate": "Один швидкий крок 💕 Підпишись на мій відкритий канал — там будуть нові пости й оновлення.\n\nПісля підписки натисни <b>«Я підписався»</b>.",
        "public_not_member": "Я поки не бачу підписку 👀 Підпишись і натисни ще раз.",
        "public_unavailable": "Не можу зараз перевірити підписку. Напиши мені трохи пізніше або повідом про це в чаті.",
        "public_ok": "Бачу тебе 💕 Заходь)",
        "welcome": "Привіт, {name}) Це мій особистий бот 💕\n\nТут можеш написати мені, подивитися приват або керувати своїм доступом.",
        "menu": "Що хочеш? 👀",
        "settings": "<b>Налаштування</b>\nРегіон: <b>{region}</b>\nМова: <b>{language}</b>",
        "invoice_error": "Не можу зараз відкрити оплату. Спробуй трохи пізніше.",
        "paid_chat_prompt": "Напиши повідомлення у відповідь — воно потрапить у платний чат.",
        "write_me": "Просто напиши мені сюди повідомлення) Я побачу його 💕",
        "about": "Це мій особистий бот: тут я приймаю повідомлення, даю доступ до привату та керую підписками.",
        "not_ready": "Спочатку натисни /start і закінчи коротке налаштування 💕",
        "premium": "Приват",
        "access": "Мій доступ",
        "settings_btn": "Налаштування",
        "write_btn": "Написати мені",
        "join_public": "Підписатися",
        "check_public": "Я підписався",
        "channel_join": "Зайти в приватний канал",
        "channel_unavailable": "Не можу зараз створити доступ до приватного каналу. Напиши мені сюди — я перевірю.",
        "access_requires_plan": "Активного доступу поки немає. Можеш обрати формат у «Приват» 💕",
        "payment_support": "Напиши, що саме не спрацювало з оплатою — я побачу повідомлення.",
        "activated": "<b>{plan} активовано 💕</b>\nДоступ до <b>{until}</b>.",
        "payment_success": "✅ <b>Оплату отримано — {amount} ⭐</b>\n<b>{plan}</b> активовано до <b>{until}</b>.\n\nДоступ уже готовий — кнопки нижче. Якщо у твоєму форматі є чат, просто напиши сюди 💕",
        "manage_subscription": "Керування підпискою",
        "cancel_renewal": "Вимкнути продовження",
        "resume_renewal": "Увімкнути продовження",
        "renewal_canceled": "Автопродовження вимкнено. Доступ працює до {until}.",
        "renewal_resumed": "Автопродовження знову увімкнено. Поточний доступ до {until}.",
        "no_subscription": "Активної регулярної підписки немає.",
        "call_btn": "Запросити дзвінок",
        "call_requires_plan": "Дзвінки доступні в особистому форматі 🖤",
        "call_limit": "На цей оплачений період дві заявки вже використані.",
        "call_requested": "Запит отримала 💕 Напишу тобі, щоб узгодити час.",
    },
    "ru": {
        "region_prompt": "Выбери регион для цен в Stars. Сейчас: <b>{region}</b>. Подтверди или измени 👇",
        "region_choose": "Выбери свой регион — от него зависит цена в Stars 👇",
        "region_saved": "Хорошо, регион поменяла на {region} 💕",
        "language_choose": "На каком языке тебе удобнее со мной?",
        "language_saved": "Готово, язык поменяла)",
        "public_gate": "Один быстрый шаг 💕 Подпишись на мой открытый канал — там будут новые посты и обновления.\n\nПосле подписки нажми <b>«Я подписался»</b>.",
        "public_not_member": "Я пока не вижу подписку 👀 Подпишись и нажми ещё раз.",
        "public_unavailable": "Не могу сейчас проверить подписку. Напиши мне чуть позже или сообщи об этом в чат.",
        "public_ok": "Вижу тебя 💕 Заходи)",
        "welcome": "Привет, {name}) Это мой личный бот 💕\n\nТут можешь написать мне, посмотреть приват или управлять своим доступом.",
        "menu": "Что хочешь? 👀",
        "settings": "<b>Настройки</b>\nРегион: <b>{region}</b>\nЯзык: <b>{language}</b>",
        "invoice_error": "Не получается открыть оплату. Попробуй немного позже.",
        "paid_chat_prompt": "Ответь на это сообщение — оно попадёт в платный чат.",
        "write_me": "Просто напиши мне сюда сообщение) Я его увижу 💕",
        "about": "Это мой личный бот: здесь я принимаю сообщения, даю доступ к привату и управляю подписками.",
        "not_ready": "Сначала нажми /start и закончи короткую настройку 💕",
        "premium": "Приват",
        "access": "Мой доступ",
        "settings_btn": "Настройки",
        "write_btn": "Написать мне",
        "join_public": "Подписаться",
        "check_public": "Я подписался",
        "channel_join": "Зайти в приватный канал",
        "channel_unavailable": "Не могу сейчас создать доступ к приватному каналу. Напиши мне сюда — я проверю.",
        "access_requires_plan": "Активного доступа пока нет. Можешь выбрать формат в «Приват» 💕",
        "payment_support": "Напиши, что именно не сработало с оплатой — я увижу сообщение.",
        "activated": "<b>{plan} активирован 💕</b>\nДоступ до <b>{until}</b>.",
        "payment_success": "✅ <b>Оплата получена — {amount} ⭐</b>\n<b>{plan}</b> активирован до <b>{until}</b>.\n\nДоступ уже готов — кнопки ниже. Если в твоём формате есть чат, просто напиши сюда 💕",
        "manage_subscription": "Управление подпиской",
        "cancel_renewal": "Отключить продление",
        "resume_renewal": "Включить продление",
        "renewal_canceled": "Автопродление отключено. Доступ работает до {until}.",
        "renewal_resumed": "Автопродление снова включено. Текущий доступ до {until}.",
        "no_subscription": "Активной регулярной подписки нет.",
        "call_btn": "Запросить звонок",
        "call_requires_plan": "Звонки доступны в личном формате 🖤",
        "call_limit": "На этот оплаченный период две заявки уже использованы.",
        "call_requested": "Заявку получила 💕 Напишу тебе, чтобы согласовать время.",
    },
    "en": {
        "region_prompt": "Choose your pricing region. Current: <b>{region}</b>. Confirm or change 👇",
        "region_choose": "Choose your region — it sets your price in Stars 👇",
        "region_saved": "Done, I changed your region to {region} 💕",
        "language_choose": "Which language is easier for you?",
        "language_saved": "Done, language changed)",
        "public_gate": "One quick step 💕 Join my public channel for new posts and updates.\n\nThen tap <b>“I joined”</b>.",
        "public_not_member": "I don't see the subscription yet 👀 Join and tap again.",
        "public_unavailable": "I can't verify the channel right now. Try a little later or message me here.",
        "public_ok": "I see you 💕 Come in)",
        "welcome": "Hey, {name}) This is my personal bot 💕\n\nYou can message me here, open the private options, or manage your access.",
        "menu": "What do you want? 👀",
        "settings": "<b>Settings</b>\nRegion: <b>{region}</b>\nLanguage: <b>{language}</b>",
        "invoice_error": "Payment is temporarily unavailable. Please try again shortly.",
        "paid_chat_prompt": "Reply to this message to use your paid chat.",
        "write_me": "Just send me a message here) I'll see it 💕",
        "about": "This is my personal bot: messages, private access and subscription management are all here.",
        "not_ready": "Tap /start first and finish the quick setup 💕",
        "premium": "Private",
        "access": "My access",
        "settings_btn": "Settings",
        "write_btn": "Message me",
        "join_public": "Join channel",
        "check_public": "I joined",
        "channel_join": "Join the private channel",
        "channel_unavailable": "I can't create the private-channel access right now. Message me here and I'll check it.",
        "access_requires_plan": "You don't have active access yet. Open “Private” to choose a format 💕",
        "payment_support": "Tell me what went wrong with the payment — I'll see your message.",
        "activated": "<b>{plan} activated 💕</b>\nAccess until <b>{until}</b>.",
        "payment_success": "✅ <b>Payment received — {amount} ⭐</b>\n<b>{plan}</b> is active until <b>{until}</b>.\n\nYour access is ready — use the buttons below. If your plan includes chat, just message here 💕",
        "manage_subscription": "Manage subscription",
        "cancel_renewal": "Turn off renewal",
        "resume_renewal": "Turn renewal back on",
        "renewal_canceled": "Automatic renewal is off. Access stays active until {until}.",
        "renewal_resumed": "Automatic renewal is back on. Current access is active until {until}.",
        "no_subscription": "There is no active recurring subscription.",
        "call_btn": "Request a call",
        "call_requires_plan": "Calls are available in the personal format 🖤",
        "call_limit": "Both call requests for this paid period have already been used.",
        "call_requested": "Got it 💕 I'll message you to arrange a time.",
    },
    "de": {
        "region_prompt": "Wähle deine Preisregion. Aktuell: <b>{region}</b>. Bestätigen oder ändern 👇",
        "region_choose": "Wähle deine Region — davon hängt der Preis in Stars ab 👇",
        "region_saved": "Okay, Region auf {region} geändert 💕",
        "language_choose": "Welche Sprache ist für dich angenehmer?",
        "language_saved": "Fertig, Sprache geändert)",
        "public_gate": "Nur ein kurzer Schritt 💕 Tritt meinem öffentlichen Kanal für neue Posts und Updates bei.\n\nDanach tippe auf <b>„Ich bin dabei“</b>.",
        "public_not_member": "Ich sehe das Abo noch nicht 👀 Tritt bei und versuch es noch einmal.",
        "public_unavailable": "Ich kann das Abo gerade nicht prüfen. Versuch es später noch einmal oder schreib mir hier.",
        "public_ok": "Ich sehe dich 💕 Komm rein)",
        "welcome": "Hey, {name}) Das ist mein persönlicher Bot 💕\n\nDu kannst mir hier schreiben, den privaten Bereich ansehen oder deinen Zugang verwalten.",
        "menu": "Was möchtest du? 👀",
        "settings": "<b>Einstellungen</b>\nRegion: <b>{region}</b>\nSprache: <b>{language}</b>",
        "invoice_error": "Die Zahlung ist momentan nicht verfügbar. Bitte versuche es später erneut.",
        "paid_chat_prompt": "Antworte auf diese Nachricht, um den bezahlten Chat zu nutzen.",
        "write_me": "Schreib mir einfach hier) Ich sehe deine Nachricht 💕",
        "about": "Das ist mein persönlicher Bot für Nachrichten, privaten Zugang und Abos.",
        "not_ready": "Tippe zuerst auf /start und beende die kurze Einrichtung 💕",
        "premium": "Privat",
        "access": "Mein Zugang",
        "settings_btn": "Einstellungen",
        "write_btn": "Mir schreiben",
        "join_public": "Kanal beitreten",
        "check_public": "Ich bin dabei",
        "channel_join": "Privatem Kanal beitreten",
        "channel_unavailable": "Ich kann den privaten Zugang gerade nicht erstellen. Schreib mir hier, dann prüfe ich es.",
        "access_requires_plan": "Du hast noch keinen aktiven Zugang. Unter „Privat“ kannst du ein Format wählen 💕",
        "payment_support": "Schreib mir, was bei der Zahlung nicht funktioniert hat — ich sehe deine Nachricht.",
        "activated": "<b>{plan} aktiviert 💕</b>\nZugang bis <b>{until}</b>.",
        "payment_success": "✅ <b>Zahlung erhalten — {amount} ⭐</b>\n<b>{plan}</b> ist bis <b>{until}</b> aktiv.\n\nDein Zugang ist bereit — nutze die Buttons unten. Wenn dein Tarif Chat enthält, schreib einfach hier 💕",
        "manage_subscription": "Abo verwalten",
        "cancel_renewal": "Verlängerung ausschalten",
        "resume_renewal": "Verlängerung einschalten",
        "renewal_canceled": "Automatische Verlängerung ist aus. Zugang bis {until}.",
        "renewal_resumed": "Automatische Verlängerung ist wieder an. Zugang bis {until}.",
        "no_subscription": "Kein aktives wiederkehrendes Abo.",
        "call_btn": "Anruf anfragen",
        "call_requires_plan": "Anrufe sind im persönlichen Format verfügbar 🖤",
        "call_limit": "Beide Anfragen für diesen Zeitraum wurden bereits genutzt.",
        "call_requested": "Hab's gesehen 💕 Ich schreibe dir wegen der Zeit.",
    },
    "fr": {
        "region_prompt": "Choisis ta région tarifaire. Actuelle : <b>{region}</b>. Confirme ou change 👇",
        "region_choose": "Choisis ta région — elle détermine le prix en Stars 👇",
        "region_saved": "C'est bon, région changée en {region} 💕",
        "language_choose": "Quelle langue te convient le mieux ?",
        "language_saved": "C'est fait, langue changée)",
        "public_gate": "Une petite étape 💕 Rejoins mon canal public pour les nouveaux posts et mises à jour.\n\nPuis appuie sur <b>« J'ai rejoint »</b>.",
        "public_not_member": "Je ne vois pas encore l'abonnement 👀 Rejoins le canal et réessaie.",
        "public_unavailable": "Je ne peux pas vérifier le canal maintenant. Réessaie un peu plus tard ou écris-moi ici.",
        "public_ok": "Je te vois 💕 Entre)",
        "welcome": "Coucou, {name}) C'est mon bot personnel 💕\n\nTu peux m'écrire ici, voir le privé ou gérer ton accès.",
        "menu": "Tu veux quoi ? 👀",
        "settings": "<b>Réglages</b>\nRégion : <b>{region}</b>\nLangue : <b>{language}</b>",
        "invoice_error": "Le paiement est temporairement indisponible. Réessaie un peu plus tard.",
        "paid_chat_prompt": "Réponds à ce message pour utiliser ton chat payant.",
        "write_me": "Écris-moi simplement ici) Je verrai ton message 💕",
        "about": "C'est mon bot personnel pour les messages, l'accès privé et les abonnements.",
        "not_ready": "Appuie d'abord sur /start et termine le réglage rapide 💕",
        "premium": "Privé",
        "access": "Mon accès",
        "settings_btn": "Réglages",
        "write_btn": "M'écrire",
        "join_public": "Rejoindre le canal",
        "check_public": "J'ai rejoint",
        "channel_join": "Rejoindre le canal privé",
        "channel_unavailable": "Je ne peux pas créer l'accès privé maintenant. Écris-moi ici et je vérifierai.",
        "access_requires_plan": "Tu n'as pas encore d'accès actif. Ouvre « Privé » pour choisir une formule 💕",
        "payment_support": "Dis-moi ce qui a bloqué avec le paiement — je verrai ton message.",
        "activated": "<b>{plan} activé 💕</b>\nAccès jusqu'au <b>{until}</b>.",
        "payment_success": "✅ <b>Paiement reçu — {amount} ⭐</b>\n<b>{plan}</b> est actif jusqu'au <b>{until}</b>.\n\nTon accès est prêt — utilise les boutons ci-dessous. Si ta formule inclut le chat, écris simplement ici 💕",
        "manage_subscription": "Gérer l'abonnement",
        "cancel_renewal": "Désactiver le renouvellement",
        "resume_renewal": "Réactiver le renouvellement",
        "renewal_canceled": "Renouvellement automatique désactivé. Accès jusqu'au {until}.",
        "renewal_resumed": "Renouvellement automatique réactivé. Accès jusqu'au {until}.",
        "no_subscription": "Aucun abonnement récurrent actif.",
        "call_btn": "Demander un appel",
        "call_requires_plan": "Les appels sont disponibles dans la formule personnelle 🖤",
        "call_limit": "Les deux demandes de ce cycle ont déjà été utilisées.",
        "call_requested": "C'est noté 💕 Je t'écris pour fixer l'heure.",
    },
    "es": {
        "region_prompt": "Elige tu región de precios. Actual: <b>{region}</b>. Confirma o cambia 👇",
        "region_choose": "Elige tu región — de eso depende el precio en Stars 👇",
        "region_saved": "Listo, cambié tu región a {region} 💕",
        "language_choose": "¿En qué idioma te resulta más cómodo hablar conmigo?",
        "language_saved": "Listo, idioma cambiado)",
        "public_gate": "Un paso rápido 💕 Únete a mi canal público para ver nuevas publicaciones y novedades.\n\nDespués pulsa <b>«Ya me uní»</b>.",
        "public_not_member": "Todavía no veo la suscripción 👀 Únete y prueba otra vez.",
        "public_unavailable": "No puedo verificar el canal ahora. Inténtalo más tarde o escríbeme aquí.",
        "public_ok": "Te veo 💕 Entra)",
        "welcome": "Hola, {name}) Este es mi bot personal 💕\n\nPuedes escribirme aquí, ver el privado o gestionar tu acceso.",
        "menu": "¿Qué quieres? 👀",
        "settings": "<b>Ajustes</b>\nRegión: <b>{region}</b>\nIdioma: <b>{language}</b>",
        "invoice_error": "El pago no está disponible temporalmente. Inténtalo más tarde.",
        "paid_chat_prompt": "Responde a este mensaje para usar tu chat de pago.",
        "write_me": "Solo escríbeme aquí) Veré tu mensaje 💕",
        "about": "Este es mi bot personal para mensajes, acceso privado y suscripciones.",
        "not_ready": "Pulsa /start primero y termina la configuración rápida 💕",
        "premium": "Privado",
        "access": "Mi acceso",
        "settings_btn": "Ajustes",
        "write_btn": "Escribirme",
        "join_public": "Unirme al canal",
        "check_public": "Ya me uní",
        "channel_join": "Entrar al canal privado",
        "channel_unavailable": "No puedo crear el acceso privado ahora. Escríbeme aquí y lo revisaré.",
        "access_requires_plan": "Aún no tienes acceso activo. Abre «Privado» para elegir una opción 💕",
        "payment_support": "Dime qué falló con el pago — veré tu mensaje.",
        "activated": "<b>{plan} activado 💕</b>\nAcceso hasta <b>{until}</b>.",
        "payment_success": "✅ <b>Pago recibido — {amount} ⭐</b>\n<b>{plan}</b> está activo hasta <b>{until}</b>.\n\nTu acceso ya está listo — usa los botones de abajo. Si tu plan incluye chat, escribe aquí 💕",
        "manage_subscription": "Gestionar suscripción",
        "cancel_renewal": "Desactivar renovación",
        "resume_renewal": "Activar renovación",
        "renewal_canceled": "Renovación automática desactivada. Acceso hasta {until}.",
        "renewal_resumed": "Renovación automática activada de nuevo. Acceso hasta {until}.",
        "no_subscription": "No hay una suscripción recurrente activa.",
        "call_btn": "Solicitar llamada",
        "call_requires_plan": "Las llamadas están disponibles en el formato personal 🖤",
        "call_limit": "Ya se usaron las dos solicitudes de este período.",
        "call_requested": "Lo vi 💕 Te escribiré para acordar la hora.",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    bank = TEXTS.get(lang) or TEXTS["en"]
    value = bank.get(key) or TEXTS["en"].get(key) or key
    return value.format(**kwargs) if kwargs else value
