from __future__ import annotations


TEXTS: dict[str, dict[str, str]] = {
    "ru": {
        "welcome": "Привет, <b>{name}</b>. Я Вика. Просто напиши, что у тебя на уме — отвечу здесь.",
        "menu": "Напиши мне сообщение или выбери действие:",
        "premium": "Premium",
        "public_channel": "Telegram-канал",
        "about_button": "Инфо",
        "about": (
            "<b>О сервисе</b>\n\nВика — виртуальный AI-собеседник. Ответы создаёт языковая модель, "
            "поэтому она может ошибаться. Сообщения сохраняются для истории и памяти. "
            "Сервис не выдаёт AI за человека и не заменяет близких или специалистов."
        ),
        "not_ready": "Нажми /start, и можно сразу общаться.",
        "ai_error": "Сейчас не получилось ответить. Попробуй ещё раз через минуту.",
        "premium_nudge": "Если хочешь больше сообщений и более сильную память — загляни в Premium ✨",
        "channel_nudge": "Кстати, в Telegram-канале есть ещё материалы и обновления 📢",
        "proactive": "Как прошёл твой день — одним честным предложением?",
    },
    "uk": {
        "welcome": "Привіт, <b>{name}</b>. Я Віка. Просто напиши, що в тебе на думці — відповім тут.",
        "menu": "Напиши мені повідомлення або обери дію:",
        "premium": "Premium",
        "public_channel": "Telegram-канал",
        "about_button": "Інфо",
        "about": (
            "<b>Про сервіс</b>\n\nВіка — віртуальний AI-співрозмовник. Відповіді створює мовна модель, "
            "тому вона може помилятися. Повідомлення зберігаються для історії та пам'яті. "
            "Сервіс не видає AI за людину й не замінює близьких або фахівців."
        ),
        "not_ready": "Натисни /start — і можна одразу спілкуватися.",
        "ai_error": "Зараз не вдалося відповісти. Спробуй ще раз за хвилину.",
        "premium_nudge": "Якщо хочеш більше повідомлень і сильнішу пам'ять — зазирни в Premium ✨",
        "channel_nudge": "До речі, у Telegram-каналі є ще матеріали й оновлення 📢",
        "proactive": "Як минув твій день — одним чесним реченням?",
    },
    "en": {
        "welcome": "Hi, <b>{name}</b>. I'm Vika. Just tell me what's on your mind and I'll reply here.",
        "menu": "Send me a message or choose an option:",
        "premium": "Premium",
        "public_channel": "Telegram channel",
        "about_button": "Info",
        "about": (
            "<b>About the service</b>\n\nVika is a virtual AI conversation assistant. Replies are generated by a "
            "language model and may be wrong. Messages are stored for conversation history and memory. "
            "The service does not present AI as human or replace people or qualified professionals."
        ),
        "not_ready": "Tap /start and you can chat right away.",
        "ai_error": "I couldn't reply just now. Please try again in a minute.",
        "premium_nudge": "Want more messages and stronger memory? Take a look at Premium ✨",
        "channel_nudge": "By the way, the Telegram channel has more content and updates 📢",
        "proactive": "How did your day go, in one honest sentence?",
    },
    "es": {
        "welcome": "Hola, <b>{name}</b>. Soy Vika. Cuéntame qué tienes en mente y te responderé aquí.",
        "menu": "Envíame un mensaje o elige una opción:",
        "premium": "Premium",
        "public_channel": "Canal de Telegram",
        "about_button": "Información",
        "about": (
            "<b>Sobre el servicio</b>\n\nVika es una asistente virtual de conversación con IA. Las respuestas "
            "las genera un modelo de lenguaje y pueden contener errores. Los mensajes se guardan para el historial "
            "y la memoria. El servicio no presenta la IA como una persona ni sustituye a personas o profesionales."
        ),
        "not_ready": "Pulsa /start y podrás conversar de inmediato.",
        "ai_error": "No pude responder ahora. Inténtalo de nuevo en un minuto.",
        "premium_nudge": "¿Quieres más mensajes y mejor memoria? Descubre Premium ✨",
        "channel_nudge": "Por cierto, el canal de Telegram tiene más contenido y novedades 📢",
        "proactive": "¿Cómo fue tu día, en una frase sincera?",
    },
    "de": {
        "welcome": "Hallo, <b>{name}</b>. Ich bin Vika. Schreib einfach, was dich beschäftigt — ich antworte hier.",
        "menu": "Schreib mir eine Nachricht oder wähle eine Option:",
        "premium": "Premium",
        "public_channel": "Telegram-Kanal",
        "about_button": "Info",
        "about": (
            "<b>Über den Dienst</b>\n\nVika ist eine virtuelle KI-Gesprächsassistentin. Antworten werden von "
            "einem Sprachmodell erzeugt und können falsch sein. Nachrichten werden für Verlauf und Erinnerung "
            "gespeichert. Der Dienst gibt KI nicht als Menschen aus und ersetzt keine Menschen oder Fachpersonen."
        ),
        "not_ready": "Tippe auf /start, dann kannst du sofort schreiben.",
        "ai_error": "Ich konnte gerade nicht antworten. Versuche es in einer Minute erneut.",
        "premium_nudge": "Mehr Nachrichten und stärkere Erinnerung? Schau dir Premium an ✨",
        "channel_nudge": "Im Telegram-Kanal gibt es übrigens weitere Inhalte und Updates 📢",
        "proactive": "Wie war dein Tag — in einem ehrlichen Satz?",
    },
    "fr": {
        "welcome": "Bonjour, <b>{name}</b>. Je suis Vika. Écris simplement ce que tu as en tête, je répondrai ici.",
        "menu": "Envoie-moi un message ou choisis une option :",
        "premium": "Premium",
        "public_channel": "Canal Telegram",
        "about_button": "Infos",
        "about": (
            "<b>À propos du service</b>\n\nVika est une assistante virtuelle de conversation basée sur l'IA. "
            "Les réponses sont générées par un modèle de langage et peuvent être erronées. Les messages sont "
            "conservés pour l'historique et la mémoire. Le service ne présente pas l'IA comme une personne et "
            "ne remplace ni les proches ni les professionnels."
        ),
        "not_ready": "Appuie sur /start et tu pourras discuter immédiatement.",
        "ai_error": "Je n'ai pas pu répondre. Réessaie dans une minute.",
        "premium_nudge": "Tu veux plus de messages et une meilleure mémoire ? Découvre Premium ✨",
        "channel_nudge": "Au fait, le canal Telegram contient d'autres contenus et actualités 📢",
        "proactive": "Comment s'est passée ta journée, en une phrase sincère ?",
    },
}


def t(lang: str, key: str, **values: object) -> str:
    locale = TEXTS.get(lang, TEXTS["en"])
    template = locale.get(key, TEXTS["en"].get(key, key))
    return template.format(**values)
